name: Build and deploy to Prod

on:
  workflow_dispatch:

jobs:
  cd:
    name: Continuous deployment

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install Fly
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5

      - name: Deploy to Fly.io
        run: flyctl deploy --config ./fly.toml --dockerfile ./Dockerfile --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
